services:
  mypersonalgit:
    image: fennch/mypersonalgit:latest
    build: .
    container_name: mypersonalgit
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - mypersonalgit-repos:/repos
      - mypersonalgit-data:/data
      - mypersonalgit-uploads:/app/wwwroot/uploads
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - ConnectionStrings__Default=Data Source=/data/mypersonalgit.db

volumes:
  mypersonalgit-repos:
  mypersonalgit-data:
  mypersonalgit-uploads:
