// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyPersonalGit.Data;

#nullable disable

namespace MyPersonalGit.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260318220000_AddOAuth2ProviderWebAuthnSspiAGit")]
    partial class AddOAuth2ProviderWebAuthnSspiAGit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.12");

            modelBuilder.Entity("MyPersonalGit.Models.OAuth2App", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<string>("ClientId").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("ClientSecret").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("Name").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("Description").HasColumnType("TEXT");
                    b.Property<string>("RedirectUri").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("Owner").IsRequired().HasColumnType("TEXT");
                    b.Property<bool>("IsConfidential").HasColumnType("INTEGER");
                    b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                    b.Property<DateTime>("UpdatedAt").HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("ClientId").IsUnique();
                    b.ToTable("OAuth2Apps");
                });

            modelBuilder.Entity("MyPersonalGit.Models.WebAuthnCredential", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<string>("Username").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("Name").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("CredentialId").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("PublicKey").IsRequired().HasColumnType("TEXT");
                    b.Property<long>("SignCount").HasColumnType("INTEGER");
                    b.Property<string>("AaGuid").HasColumnType("TEXT");
                    b.Property<bool>("IsPlatform").HasColumnType("INTEGER");
                    b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                    b.Property<DateTime?>("LastUsedAt").HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("Username", "CredentialId").IsUnique();
                    b.ToTable("WebAuthnCredentials");
                });
#pragma warning restore 612, 618
        }
    }
}
