// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyPersonalGit.Data;

#nullable disable

namespace MyPersonalGit.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260316100000_AddMatrixTimeoutInputs")]
    partial class AddMatrixTimeoutInputs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
