// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyPersonalGit.Data;

#nullable disable

namespace MyPersonalGit.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260315000000_AddSshServerAndLdap")]
    partial class AddSshServerAndLdap
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.12");

            // This migration only adds columns to SystemSettings.
            // The full model is defined in AppDbContextModelSnapshot.cs.
            // Intentionally minimal — EF Core uses the snapshot for the current model state.
#pragma warning restore 612, 618
        }
    }
}
