// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyPersonalGit.Data;

#nullable disable

namespace MyPersonalGit.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260319200000_AddRequireSignedCommits")]
    partial class AddRequireSignedCommits
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.12");

            modelBuilder.Entity("MyPersonalGit.Models.BranchProtectionRule", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<string>("RepoName").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("BranchPattern").IsRequired().HasColumnType("TEXT");
                    b.Property<bool>("RequirePullRequest").HasColumnType("INTEGER");
                    b.Property<int>("RequiredApprovals").HasColumnType("INTEGER");
                    b.Property<bool>("RequireStatusChecks").HasColumnType("INTEGER");
                    b.Property<string>("RequiredStatusChecks").IsRequired().HasColumnType("TEXT");
                    b.Property<bool>("PreventForcePush").HasColumnType("INTEGER");
                    b.Property<bool>("PreventDeletion").HasColumnType("INTEGER");
                    b.Property<bool>("RequireLinearHistory").HasColumnType("INTEGER");
                    b.Property<bool>("RestrictPushes").HasColumnType("INTEGER");
                    b.Property<string>("AllowedPushUsers").IsRequired().HasColumnType("TEXT");
                    b.Property<bool>("RequireCodeOwnersApproval").HasColumnType("INTEGER");
                    b.Property<bool>("RequireSignedCommits").HasColumnType("INTEGER");
                    b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                    b.Property<DateTime>("UpdatedAt").HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.ToTable("BranchProtectionRules");
                });
#pragma warning restore 612, 618
        }
    }
}
