// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyPersonalGit.Data;

#nullable disable

namespace MyPersonalGit.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260319210000_AddPinnedReposAndProtectedFiles")]
    partial class AddPinnedReposAndProtectedFiles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.12");

            modelBuilder.Entity("MyPersonalGit.Models.PinnedRepository", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<string>("Username").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("RepoName").IsRequired().HasColumnType("TEXT");
                    b.Property<int>("SortOrder").HasColumnType("INTEGER");
                    b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("Username", "RepoName").IsUnique();
                    b.ToTable("PinnedRepositories");
                });
#pragma warning restore 612, 618
        }
    }
}
