using System.Security.Cryptography;
using System.Text;
using Microsoft.EntityFrameworkCore;
using MyPersonalGit.Models;

namespace MyPersonalGit.Data;

public interface ISshAuthService
{
    Task<string?> AuthenticateByKeyAsync(string keyContent);
    Task<string?> AuthenticateByFingerprintAsync(string fingerprint);
    Task<DeployKeyValidationResult?> AuthenticateDeployKeyByFingerprintAsync(string fingerprint, string repoPath);
    Task RegenerateAuthorizedKeysAsync();
    string GetAuthorizedKeysPath();
}

/// <summary>
/// Manages SSH key authentication for Git operations.
/// Generates and maintains an authorized_keys file from the database,
/// and provides lookup endpoints for OpenSSH's AuthorizedKeysCommand.
/// </summary>
public class SshAuthService : ISshAuthService
{
    private readonly IDbContextFactory<AppDbContext> _dbFactory;
    private readonly IDeployKeyService _deployKeyService;
    private readonly ILogger<SshAuthService> _logger;
    private readonly IConfiguration _config;
    private readonly string _authorizedKeysPath;
    private readonly string _dataDir;

    public SshAuthService(IDbContextFactory<AppDbContext> dbFactory, IDeployKeyService deployKeyService, ILogger<SshAuthService> logger, IConfiguration config)
    {
        _dbFactory = dbFactory;
        _deployKeyService = deployKeyService;
        _logger = logger;
        _config = config;

        _dataDir = config["Ssh:DataDir"] ?? Path.Combine(
            Environment.GetFolderPath(Environment.SpecialFolder.UserProfile),
            ".mypersonalgit", "ssh");

        _authorizedKeysPath = config["Ssh:AuthorizedKeysPath"]
            ?? Path.Combine(_dataDir, "authorized_keys");
    }

    public string GetAuthorizedKeysPath() => _authorizedKeysPath;

    /// <summary>
    /// Look up the username that owns a given SSH public key.
    /// Used by the AuthorizedKeysCommand or the SSH auth API endpoint.
    /// </summary>
    public async Task<string?> AuthenticateByKeyAsync(string keyContent)
    {
        if (string.IsNullOrWhiteSpace(keyContent))
            return null;

        var fingerprint = GenerateFingerprint(keyContent.Trim());

        return await AuthenticateByFingerprintAsync(fingerprint);
    }

    /// <summary>
    /// Look up the username that owns a key with the given fingerprint.
    /// </summary>
    public async Task<string?> AuthenticateByFingerprintAsync(string fingerprint)
    {
        using var db = _dbFactory.CreateDbContext();

        var sshKey = await db.SshKeys
            .FirstOrDefaultAsync(k => k.Fingerprint == fingerprint);

        if (sshKey == null)
            return null;

        // Update last used timestamp
        sshKey.LastUsed = DateTime.UtcNow;
        await db.SaveChangesAsync();

        _logger.LogInformation("SSH key authenticated for user {Username} (fingerprint: {Fingerprint})",
            sshKey.Username, fingerprint);

        return sshKey.Username;
    }

    /// <summary>
    /// Authenticate a deploy key by fingerprint for a specific repository path.
    /// Deploy keys grant access only to their associated repository.
    /// </summary>
    public async Task<DeployKeyValidationResult?> AuthenticateDeployKeyByFingerprintAsync(string fingerprint, string repoPath)
    {
        return await _deployKeyService.ValidateDeployKeyAsync(fingerprint, repoPath);
    }

    /// <summary>
    /// Regenerate the authorized_keys file from all SSH keys in the database.
    /// Each entry uses a command= prefix that restricts the key to git operations
    /// and identifies the user via the key ID.
    /// </summary>
    public async Task RegenerateAuthorizedKeysAsync()
    {
        using var db = _dbFactory.CreateDbContext();

        var allKeys = await db.SshKeys.ToListAsync();

        var dir = Path.GetDirectoryName(_authorizedKeysPath);
        if (!string.IsNullOrEmpty(dir) && !Directory.Exists(dir))
            Directory.CreateDirectory(dir);

        var sb = new StringBuilder();
        sb.AppendLine("# Auto-generated by MyPersonalGit — do not edit manually");
        sb.AppendLine($"# Generated at {DateTime.UtcNow:u}");
        sb.AppendLine($"# {allKeys.Count} key(s)");
        sb.AppendLine();

        var serverUrl = _config["Ssh:ServerUrl"] ?? "http://localhost:5146";
        var gitShellPath = _config["Ssh:GitShellPath"] ?? "/usr/bin/mypersonalgit-shell";

        foreach (var key in allKeys)
        {
            // Format: command="<shell> <key-id> <username>",no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty <key-type> <key-data> <comment>
            var restrictions = "no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty";
            var command = $"command=\"{gitShellPath} {key.Id} {key.Username}\"";
            sb.AppendLine($"{command},{restrictions} {key.Key.Trim()}");
        }

        await File.WriteAllTextAsync(_authorizedKeysPath, sb.ToString());

        _logger.LogInformation("Regenerated authorized_keys with {Count} keys at {Path}",
            allKeys.Count, _authorizedKeysPath);
    }

    private static string GenerateFingerprint(string key)
    {
        var parts = key.Trim().Split(' ');
        var keyData = parts.Length >= 2 ? parts[1] : key;
        using var sha256 = SHA256.Create();
        try
        {
            var bytes = Convert.FromBase64String(keyData);
            var hash = sha256.ComputeHash(bytes);
            return "SHA256:" + Convert.ToBase64String(hash).TrimEnd('=');
        }
        catch
        {
            var hash = sha256.ComputeHash(Encoding.UTF8.GetBytes(key));
            return Convert.ToHexString(hash)[..16].ToLower();
        }
    }
}

/// <summary>
/// Background service that periodically regenerates the authorized_keys file
/// to keep it in sync with the database.
/// </summary>
public class AuthorizedKeysSyncService : BackgroundService
{
    private readonly IServiceScopeFactory _scopeFactory;
    private readonly ILogger<AuthorizedKeysSyncService> _logger;

    public AuthorizedKeysSyncService(IServiceScopeFactory scopeFactory, ILogger<AuthorizedKeysSyncService> logger)
    {
        _scopeFactory = scopeFactory;
        _logger = logger;
    }

    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        _logger.LogInformation("Authorized keys sync service started");

        // Initial sync on startup
        await SyncKeys();

        while (!stoppingToken.IsCancellationRequested)
        {
            await Task.Delay(TimeSpan.FromMinutes(5), stoppingToken);

            try
            {
                await SyncKeys();
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error syncing authorized keys");
            }
        }
    }

    private async Task SyncKeys()
    {
        using var scope = _scopeFactory.CreateScope();
        var sshAuthService = scope.ServiceProvider.GetRequiredService<ISshAuthService>();
        await sshAuthService.RegenerateAuthorizedKeysAsync();
    }
}
